name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Limpar o cache do Cypress
      - name: Clear Cypress cache
        run: npx cypress cache clear

      # Instalar as dependências do NPM, cacheá-las corretamente
      # e executar todos os testes do Cypress
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          config-file: cypress.config.js
