name: End-to-end tests 🧪
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Clear Cypress cache
        run: npx cypress cache clear

      - name: Delete cypress.json
        run: rm cypress.json || true

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          config-file: cypress.config.js
